### ISSUE TITLE
Update ./dist/ for 0.3.1 version

### ISSUE THREAD

**Issue by mrded** [Palmabit-IT/angular-cookie-law#15]
Looks like you forgot to rebuild `./dist/` for `0.3.1` version. The last update was 2 years ago.

And if you install 0.3.1 version package via `npm` it doesn't contain new changes.

**Comment by mrded** [comment]
I made a pull request here https://github.com/Palmabit-IT/angular-cookie-law/pull/16

**Comment by asarzina** [comment]
Merged. Thank you very much.
