### ISSUE TITLE
Position doesn't work

### ISSUE THREAD

**Issue by Slandais** [Palmabit-IT/angular-cookie-law#17]
Position attribute doesn't work.

In banner.js file 
https://github.com/Palmabit-IT/angular-cookie-law/blob/master/src/js/directives/banner.js
I see the line : "position: attr.position === 'bottom' ? 'bottom' : 'top', //Position of the banner. (Default: 'top')"

But in dist folder I can't see it:
https://github.com/Palmabit-IT/angular-cookie-law/blob/master/dist/angular-cookie-law.js
https://github.com/Palmabit-IT/angular-cookie-law/blob/master/dist/angular-cookie-law.min.js

*****

Will be fixed with the issue: https://github.com/Palmabit-IT/angular-cookie-law/issues/15

**Comment by asarzina** [comment]
Pull-request merged. Thanks for your contribution.
