### ISSUE TITLE
release to CDN

### ISSUE THREAD

**Issue by wholeinsoul** [Palmabit-IT/angular-cookie-law#23]
Hi @palmabit : Thank you for the repo. Can you please release the latest version to CDN ? The version on CDN is pretty old: https://www.jsdelivr.com/package/npm/angular-cookie-law

Thank you.

**Comment by asarzina** [comment]
Hi,
you can find the last version (0.5.0) at this CDN: https://cdn.jsdelivr.net/npm/@palmabit/angular-cookie-law@0.5.0/dist/angular-cookie-law.min.js
