### ISSUE TITLE
Position the bar in the footer

### ISSUE THREAD

**Issue by temuccio** [Palmabit-IT/angular-cookie-law#4]
Hello, 
I would like to position the bar cookie law in the footer.
I have changed 
`element: attr.element || 'body'`
in 
`element: attr.element || '.footer'`
but the position is always on the top of page.
I can change the style of class .footer without problem and I think that the class works fine.
Do you can help me?

**Comment by asarzina** [comment]
You should override the style of class cl-banner. See angular-cookie-law.css file.

**Comment by mrded** [comment]
Please have a look my PR https://github.com/Palmabit-IT/angular-cookie-law/pull/12

**Comment by ceccode** [comment]
Merged PR #12
