### ISSUE TITLE
attributes not working

### ISSUE THREAD

**Issue by ggiacomo** [Palmabit-IT/angular-cookie-law#6]
Only message attribute in the tag cookie-law-banner is overrided.
`<cookie-law-banner acceptButton="true" acceptText="Helloooo" message="custom message" .....`

**Comment by ggiacomo** [comment]
Solved. Had to write es 'acceptText' in this way 'accept-text'. 
You should update the doc since is not super intuitive.

**Comment by asarzina** [comment]
Thanks for your feedback
