### ISSUE TITLE
decline button

### ISSUE THREAD

**Issue by jcmag** [Palmabit-IT/angular-cookie-law#8]
Hi,
I'd like to know the behavior of the decline button: if I click on it, a cookie is set (_cle=declined), and the banner stays displayed? (shouldn't it be hidden?)

**Comment by Slandais** [comment]
+1

Yes, how close the banner if user click on decline button ?

**Comment by asarzina** [comment]
Yes, the banner should close when the decline button is pressed. I'll check this function.
Thank you

**Comment by asarzina** [comment]
https://github.com/Palmabit-IT/angular-cookie-law/pull/18
